language: cpp
env:
  global:
    - QT5_VERSION="v5.12.5"
      QT5_INSTALL_PREFIX="/usr/local/qt5-static"
matrix:
  include:
    # linux release build: gcc 9.1.0 on ubuntu 16.04
    - os: linux
      dist: xenial
      compiler: gcc
      # use qt xcb helper libraries on linux (requires libxkbcommon-dev)
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libxkbcommon-dev
      before_install:
        # force qt to use desired compiler version
        - sudo rm /usr/bin/gcc
        - sudo rm /usr/bin/g++
        - sudo ln -s /usr/bin/gcc-9 /usr/bin/gcc
        - sudo ln -s /usr/bin/g++-9 /usr/bin/g++
        - gcc --version
        - g++ --version
      env: QT5_XCB_FLAG="qt-xcb"
    # osx release build: xcode 9.4.1 [9F2000], macOS 10.13
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      # explicitly disable xcb on osx build
      env: QT5_XCB_FLAG="no-xcb"
before_script:
  # download Qt5 sources
  - git clone https://code.qt.io/qt/qt5.git
  - cd qt5
  # checkout desired version
  - git checkout $QT5_VERSION
  # only need qtbase submodule
  - git submodule update --init qtbase
  - cd ../
script:
  # build a minimal static version of qtbase & install to $QT5_INSTALL_PREFIX
  - mkdir build
  - cd build
  - ../qt5/qtbase/configure -opensource -confirm-license -prefix $QT5_INSTALL_PREFIX -release -static -silent -$QT5_XCB_FLAG -sql-sqlite -qt-zlib -qt-libjpeg -qt-libpng -qt-pcre -qt-harfbuzz -no-compile-examples -nomake tests -nomake examples -no-opengl -no-openssl -no-sql-odbc -no-icu -no-feature-concurrent -no-feature-xml -feature-testlib
  - make -j2
  - sudo make install
  # confirm qmake runs and check version number
  - $QT5_INSTALL_PREFIX/bin/qmake -v
before_deploy:
  # make tarball of installation
  tar -zcvf qt5-static-$TRAVIS_OS_NAME.tgz $QT5_INSTALL_PREFIX
deploy:
  # if commit was tagged, upload resulting tarball to github release
  provider: releases
  api_key:
    secure: TCD5ZL62jMxf5PD4IBOsxL8CQwgGiQn7+W8I8z7XAbMcP5QyeypctkE97VAz1dgfOCjBAEWqcenw/efnf8Yfh3T9HjkC8Btfs0PA8uwrsUsC5qq7uQF1YNqsRHFxMYo2OU3RDAuQ2p1kfTJsQiJbogfgBmKTgT8t6boA16pVfvAtxQAakKbZQKt7jIkKB4eFA/hxie4e+s28/TiZ/PH54rf0kGnwf7cJpj86NH4kqGoQXhmqYjIVumCc9bbpNTPRif+tMExXwEIDZQ50vWRt9FjrsVpWKK6bOhw/zi+7OdU70f/X3G6qQC6fXNECndI8+xrdo0Ie2Js4I9RYcRGp+vdTICcD85pOlFQnKYzcRWZdt2uCAgC6XCM785Nymc3SZkBD9jeK+Nh1HTUsGf2d8kVPAajWllxhtdt/oPIKNy77NbILj/R+tPsXLPjoC07jM6heVVHw7CPo3gnVmsuJvDtfIDG36KDFRfgJxRECLnj48cDLx/X4zcFJajqbDMJibUC5HYQg5pBL4+Bxkalo7jhoKKOxI2+pQaWEMFNh/aNVQu2tnKwJEhRNngt/gdAFYBR/Vmlt839/RiLrB0R5UpONVxSjRhbKAS0xwBka7CCxXAWHbCN3ferbgecVfqhys5n+kqXQBi2ofBM+zj73X9LuV2F6ef4B3oN0oPqRrwQ=
  file:
    - qt5-static-$TRAVIS_OS_NAME.tgz
  skip_cleanup: true
  on:
    repo: sanjay900/guitar-configurator
    tags: true
    all_branches: true
notifications:
  email: false