sudo: required
dist: trusty

language: node_js

matrix:
  include:
    - os: osx
    - os: windows
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

node_js:
  - "10"

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libusb-dev
      - libudev-dev

install:
  - nvm install 10
  - npm install

script:
- npm run dist