language: cpp
matrix:
  include:
  - os: osx
    osx_image: xcode9.2

    compiler: clang

    script:
      - ./unixbuild.sh

    deploy:
      provider: releases
      skip_cleanup: true
      file: "dist/*.zip"
      file_glob: true
      api_key:
        secure: "WjYd93lVLKHULBpUXS/WtGrkdXyAwxHOUnLJotyDmQipAQP5Ox7Kj12JwkSJGEmVOEdcbIQJyi0QxPjn1UYbYsAt6Op8zrjnYLS4G4fMdBtcxprWzid85uTW7oAAIFs7ygMVhpzxRKpu70yNb683vbThqNmaOu6RyG9aJOLtPAg="
      on:
        tags: true

  - os: linux
    dist: trusty
    compiler: clang

    before_install:
      - sudo apt-get update -qq
      - sudo apt-get install -qq qt5-default qt5-qmake qtbase5-dev-tools cmake

    script:
      - ./unixbuild.sh

  - os: windows
    script:
      - ./unixbuild.sh

    deploy:
      provider: releases
      skip_cleanup: true
      file: "dist/*.zip"
      file_glob: true
      api_key:
        secure: "WjYd93lVLKHULBpUXS/WtGrkdXyAwxHOUnLJotyDmQipAQP5Ox7Kj12JwkSJGEmVOEdcbIQJyi0QxPjn1UYbYsAt6Op8zrjnYLS4G4fMdBtcxprWzid85uTW7oAAIFs7ygMVhpzxRKpu70yNb683vbThqNmaOu6RyG9aJOLtPAg="
      on:
        tags: true

  - os: linux
    dist: trusty
    compiler: gcc

    before_install:
      - sudo apt-get update -qq
      - sudo apt-get install -qq qt5-default qt5-qmake qtbase5-dev-tools cmake

    script:
      - ./unixbuild.sh

    deploy:
      provider: releases
      skip_cleanup: true
      file: "dist/*.zip"
      file_glob: true
      api_key:
        secure: "WjYd93lVLKHULBpUXS/WtGrkdXyAwxHOUnLJotyDmQipAQP5Ox7Kj12JwkSJGEmVOEdcbIQJyi0QxPjn1UYbYsAt6Op8zrjnYLS4G4fMdBtcxprWzid85uTW7oAAIFs7ygMVhpzxRKpu70yNb683vbThqNmaOu6RyG9aJOLtPAg="
      on:
        tags: true