image: Visual Studio 2017
environment:
  matrix:
    - arch: x64
      QT_DIR: C:\Qt\5.13.2\msvc2017_64
    - arch: x86
      QT_DIR: C:\Qt\5.13.2\msvc2017
  APPVEYOR_API_TOKEN:
    secure: 6EbQhfwu9eDqhf4aTzHog1TGDIPgFdajVfAS13n2N+c=


install:
  - git submodule update --init --recursive
  - set PATH=%PATH%;%QT_DIR%\bin;C:\Qt\QtIFW-3.0.1\bin;%cd%\build-bin\avr-gcc\bin
  - set REPO_SLUG=%APPVEYOR_REPO_NAME%
  - set TRAVIS_COMMIT=%APPVEYOR_REPO_COMMIT%
  - set TRAVIS_TAG=%APPVEYOR_REPO_TAG_NAME%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch%
before_build:
  - ps: |
      ( Invoke-RestMethod https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=20 ).builds                                                                             `
      | Where-Object {$_.status -eq "queued" -and ( $_.tag -match "continuous" ) }  |
      %{ $_.version }                                                             |
      %{
        $msg = "Found build version $_"
        Write-Host "  $msg"
        $url = "https://ci.appveyor.com/api/builds/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/$_"
        Invoke-RestMethod $url   `
          -Method Delete         `
          -Headers @{"Authorization" = "Bearer $env:APPVEYOR_API_TOKEN"};
        Write-Host "  $msg - cancelled"
      }
  - qmake -config release -tp vc -spec win32-msvc guitar-configurator.pro
configuration:
  - Release
after_build:
  - mkdir deploy
  - xcopy firmware /O/X/E/H/K/I deploy\firmware
  - xcopy binaries\win /O/X/E/H/K/I deploy\binaries
  - cp release\guitar-configurator.exe deploy
  - windeployqt deploy\guitar-configurator.exe -qmldir=.
  - xcopy /O/X/E/H/K/I deploy installer\packages\net.tangentmc.guitar_configurator\data
  - binarycreator -c installer\config\config.xml -p installer\packages win_installer_%arch%.exe
  # find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq # for debugging
  # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - powershell wget https://github.com/probonopd/uploadtool/raw/master/upload.sh -OutFile upload.sh
  - bash upload.sh win_installer_%arch%.exe
skip_tags: false