install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.13.0\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
build_script:
  - qmake -config release -tp vc -spec win32-msvc guitar-configurator.pro
  - windeployqt guitar-configurator.exe -qmldir=../
  - tree

on_success:
  # find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq # for debugging
  # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Guitar_Configurator*.AppImage*
branches:
  except:    
  - /^(?i:continuous)/