install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.13.0\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
before_build:
  - set QMAKESPEC=win32-msvc
  - qmake -config release -tp vc -spec win32-msvc guitar-configurator.pro
configuration:
  - Release
after_build:
  - mkdir deploy
  - cp guitar-configurator.exe deploy
  - windeployqt deploy/guitar-configurator.exe -qmldir=../
  - tree deploy
  - 7z a guitar-configurator_win_%arch%.zip .\deploy\*
  # find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq # for debugging
  # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh guitar-configurator_win_%arch%.zip
branches:
  except:    
  - /^(?i:continuous)/