image: Visual Studio 2017
environment:
  matrix:
    - arch: x64
      QT_DIR: C:\Qt\5.12.3\msvc2017_64
    - arch: x86
      QT_DIR: C:\Qt\5.12.3\msvc2017

install:
  - git submodule update --init --recursive
  - set PATH=%PATH%;%QT_DIR%\bin;%cd%\build\avr-gcc\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch%
before_build:
  - qmake -config release -tp vc -spec win32-msvc guitar-configurator.pro
configuration:
  - Release
after_build:
  - bash -c "cd submodules/Ardwiino && find ../../build"
  - bash -c "cd submodules/Ardwiino && ../../build/avr-gcc/bin/make.exe build-all"
  - mkdir deploy
  - mkdir deploy\firmware
  - mkdir deploy\binaries
  - cp submodules\Ardwiino\output\* deploy\firmware
  - cp -r binaries\win deploy\binaries
  - cp release\guitar-configurator.exe deploy
  - windeployqt deploy\guitar-configurator.exe -qmldir=../
  - 7z a guitar-configurator_win_%arch%.zip .\deploy\*
  # find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq # for debugging
  # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - powershell wget https://github.com/probonopd/uploadtool/raw/master/upload.sh -OutFile upload.sh
  - bash upload.sh guitar-configurator_win_%arch%.zip
branches:
  except:    
  - /^(?i:continuous)/