environment:
  matrix:
    - arch: x64
      QT_DIR: C:\Qt\5.13.0\msvc2017_64
    - arch: x86
      QT_DIR: C:\Qt\5.13.0\msvc2017
install:
  - git submodule update --init --recursive
  - set PATH=%PATH%;%QTDIR%\bin
build_script:
  - qmake -config release -tp vc -spec win32-msvc2017 guitar-configurator.pro
  - windeployqt --release -qmldir=../ guitar-configurator.exe 
  - find

on_success:
  # find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq # for debugging
  # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Guitar_Configurator*.AppImage*
branches:
  except:    
  - /^(?i:continuous)/