install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.13.0\mingw73_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - qmake guitar-configurator.pro
  - mingw32-make