import * as _ from 'c-struct';
const pins_t = {
  up: _.type.uint8,
  down: _.type.uint8,
  left: _.type.uint8,
  right: _.type.uint8,
  start: _.type.uint8,
  back: _.type.uint8,
  left_stick: _.type.uint8,
  right_stick: _.type.uint8,
  LB: _.type.uint8,
  RB: _.type.uint8,
  home: _.type.uint8,
  unused: _.type.uint8,
  a: _.type.uint8,
  b: _.type.uint8,
  x: _.type.uint8,
  y: _.type.uint8,
  lt: _.type.uint8,
  rt: _.type.uint8,
  l_x: _.type.uint8,
  l_y: _.type.uint8,
  r_x: _.type.uint8,
  r_y: _.type.uint8,
};
const axis_invert_t = {
  lt: _.type.uint8,
  rt: _.type.uint8,
  l_x: _.type.uint8,
  l_y: _.type.uint8,
  r_x: _.type.uint8,
  r_y: _.type.uint8,
};
const analogue_keys_t = {
  neg: _.type.uint8,
  pos: _.type.uint8,
};
const keys_t = {
  up: _.type.uint8,
  down: _.type.uint8,
  left: _.type.uint8,
  right: _.type.uint8,
  start: _.type.uint8,
  back: _.type.uint8,
  left_stick: _.type.uint8,
  right_stick: _.type.uint8,
  LB: _.type.uint8,
  RB: _.type.uint8,
  home: _.type.uint8,
  a: _.type.uint8,
  b: _.type.uint8,
  x: _.type.uint8,
  y: _.type.uint8,
  lt: _.type.uint8,
  rt: _.type.uint8,
  l_x: analogue_keys_t,
  l_y: analogue_keys_t,
  r_x: analogue_keys_t,
  r_y: analogue_keys_t,
};
const config_t = {
  version: _.type.uint8,
  output_type: _.type.uint8,
  input_type: _.type.uint8,
  tilt_type: _.type.uint8,
  subtype: _.type.uint8,
  pollrate: _.type.uint8,
  pins: pins_t,
  mpu_6050_orientation: _.type.uint16,
  frets_led_mode: _.type.uint8,
  map_joy_to_dpad: _.type.uint8,
  inversions: axis_invert_t,
  threshold_trigger: _.type.uint16,
  threshold_joy: _.type.uint16,
  keys: keys_t,
  cpu_freq: _.type.uint32,
  signature: _.type.uint32,
};

export type pins_t = {
  up: number,
  down: number,
  left: number,
  right: number,
  start: number,
  back: number,
  left_stick: number,
  right_stick: number,
  LB: number,
  RB: number,
  home: number,
  unused: number,
  a: number,
  b: number,
  x: number,
  y: number,
  lt: number,
  rt: number,
  l_x: number,
  l_y: number,
  r_x: number,
  r_y: number,
};
export type axis_invert_t = {
  lt: number,
  rt: number,
  l_x: number,
  l_y: number,
  r_x: number,
  r_y: number,
};
export type analogue_keys_t = {
  neg: number,
  pos: number,
};
export type keys_t = {
  up: number,
  down: number,
  left: number,
  right: number,
  start: number,
  back: number,
  left_stick: number,
  right_stick: number,
  LB: number,
  RB: number,
  home: number,
  a: number,
  b: number,
  x: number,
  y: number,
  lt: number,
  rt: number,
  l_x: analogue_keys_t,
  l_y: analogue_keys_t,
  r_x: analogue_keys_t,
  r_y: analogue_keys_t,
};
export type config_t = {
  version: number,
  output_type: number,
  input_type: number,
  tilt_type: number,
  subtype: number,
  pollrate: number,
  pins: pins_t,
  mpu_6050_orientation: number,
  frets_led_mode: number,
  map_joy_to_dpad: number,
  inversions: axis_invert_t,
  threshold_trigger: number,
  threshold_joy: number,
  keys: keys_t,
  cpu_freq: number,
  signature: number,
};
