blank_issues_enabled: false
contact_links:
  - name: Santroller
    url: https://github.com/Santroller/Santroller/issues
    about: Guitar configurators next major update is a total rewrite from the ground up and thus it has been moved to a new project.