QT.usb_private.VERSION = 0.6.2
QT.usb_private.name = QtUsb
QT.usb_private.module =
QT.usb_private.libs = $$QT_MODULE_LIB_BASE
QT.usb_private.includes = $$QT_MODULE_INCLUDE_BASE/QtUsb/0.6.2 $$QT_MODULE_INCLUDE_BASE/QtUsb/0.6.2/QtUsb
QT.usb_private.frameworks =
QT.usb_private.depends = core_private core_private usb
QT.usb_private.uses =
QT.usb_private.module_config = v2 staticlib internal_module
QT.usb_private.enabled_features =
QT.usb_private.disabled_features =
