QT.usb.VERSION = 0.6.2
QT.usb.name = QtUsb
QT.usb.module = Qt5Usb
QT.usb.libs = $$QT_MODULE_LIB_BASE
QT.usb.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/QtUsb
QT.usb.frameworks =
QT.usb.bins = $$QT_MODULE_BIN_BASE
QT.usb.depends = core
QT.usb.uses =
QT.usb.module_config = v2 staticlib
QT.usb.DEFINES = QT_USB_LIB
QT.usb.enabled_features =
QT.usb.disabled_features =
QT_CONFIG +=
QT_MODULES += usb
