export type pins_t = {
  up: number,
  down: number,
  left: number,
  right: number,
  start: number,
  back: number,
  left_stick: number,
  right_stick: number,
  LB: number,
  RB: number,
  home: number,
  unused: number,
  a: number,
  b: number,
  x: number,
  y: number,
  lt: number,
  rt: number,
  l_x: number,
  l_y: number,
  r_x: number,
  r_y: number,
  mpu_6050_interrupt: number,
};
export type axis_invert_t = {
  lt: boolean,
  rt: boolean,
  l_x: boolean,
  l_y: boolean,
  r_x: boolean,
  r_y: boolean,
};
export type analogue_keys_t = {
  neg: number,
  pos: number,
};
export type keys_t = {
  up: number,
  down: number,
  left: number,
  right: number,
  start: number,
  back: number,
  left_stick: number,
  right_stick: number,
  LB: number,
  RB: number,
  home: number,
  a: number,
  b: number,
  x: number,
  y: number,
  lt: number,
  rt: number,
  l_x: analogue_keys_t,
  l_y: analogue_keys_t,
  r_x: analogue_keys_t,
  r_y: analogue_keys_t,
};
export type config_t = {
  version: number,
  output_type: number,
  input_type: number,
  tilt_type: number,
  subtype: number,
  pollrate: number,
  pins: pins_t,
  mpu_6050_orientation: number,
  frets_led_mode: boolean,
  map_joy_to_dpad: boolean,
  inversions: axis_invert_t,
  threshold_trigger: number,
  threshold_joy: number,
  keys: keys_t,
  cpu_freq: number,
  signature: number,
};
