export type GeneratedEEPROMConfig = {
	version: number,
	output_type: number,
	input_type: number,
	tilt_type: number,
	subtype: number,
	pollrate: number,
	pins: {
		up: number,
		down: number,
		left: number,
		right: number,
		start: number,
		back: number,
		left_stick: number,
		right_stick: number,
		LB: number,
		RB: number,
		home: number,
		unused: number,
		a: number,
		b: number,
		x: number,
		y: number,
		lt: number,
		rt: number,
		l_x: number,
		l_y: number,
		r_x: number,
		r_y: number,
		mpu_6050_interrupt: number,
	},
	mpu_6050_orientation: number,
	frets_led_mode: boolean,
	map_joy_to_dpad: boolean,
	inversions: {
		lt: boolean,
		rt: boolean,
		l_x: boolean,
		l_y: boolean,
		r_x: boolean,
		r_y: boolean,
	},
	threshold_trigger: number,
	threshold_joy: number,
	keys: {
		up: number,
		down: number,
		left: number,
		right: number,
		start: number,
		back: number,
		left_stick: number,
		right_stick: number,
		LB: number,
		RB: number,
		home: number,
		a: number,
		b: number,
		x: number,
		y: number,
		lt: number,
		rt: number,
		l_x: {
			neg: number,
			pos: number,
		},
		l_y: {
			neg: number,
			pos: number,
		},
		r_x: {
			neg: number,
			pos: number,
		},
		r_y: {
			neg: number,
			pos: number,
		},
	},
	cpu_freq: number,
	signature: number,
};
