language: shell
git:
  depth: 3
install:
- sudo apt-get install -y make gcc-avr avr-libc binutils
script:
- make build-all
deploy:
  provider: releases
  api_key:
    secure: TCD5ZL62jMxf5PD4IBOsxL8CQwgGiQn7+W8I8z7XAbMcP5QyeypctkE97VAz1dgfOCjBAEWqcenw/efnf8Yfh3T9HjkC8Btfs0PA8uwrsUsC5qq7uQF1YNqsRHFxMYo2OU3RDAuQ2p1kfTJsQiJbogfgBmKTgT8t6boA16pVfvAtxQAakKbZQKt7jIkKB4eFA/hxie4e+s28/TiZ/PH54rf0kGnwf7cJpj86NH4kqGoQXhmqYjIVumCc9bbpNTPRif+tMExXwEIDZQ50vWRt9FjrsVpWKK6bOhw/zi+7OdU70f/X3G6qQC6fXNECndI8+xrdo0Ie2Js4I9RYcRGp+vdTICcD85pOlFQnKYzcRWZdt2uCAgC6XCM785Nymc3SZkBD9jeK+Nh1HTUsGf2d8kVPAajWllxhtdt/oPIKNy77NbILj/R+tPsXLPjoC07jM6heVVHw7CPo3gnVmsuJvDtfIDG36KDFRfgJxRECLnj48cDLx/X4zcFJajqbDMJibUC5HYQg5pBL4+Bxkalo7jhoKKOxI2+pQaWEMFNh/aNVQu2tnKwJEhRNngt/gdAFYBR/Vmlt839/RiLrB0R5UpONVxSjRhbKAS0xwBka7CCxXAWHbCN3ferbgecVfqhys5n+kqXQBi2ofBM+zj73X9LuV2F6ef4B3oN0oPqRrwQ=
  file_glob: true
  skip_cleanup: true
  overwrite: true
  file:
    - output/*
  on:
    repo: sanjay900/Ardwiino
    tags: true
