name: Build Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with: 
        modules: qtserialport qtquickcontrols2 
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: build and bundle
      run: |
        mkdir build
        cd build
        qmake CONFIG+=release ../
        make -j2
        cd ..
        mkdir deploy
        xcopy firmware /O/X/E/H/K/I deploy\firmware
        xcopy binaries\win /O/X/E/H/K/I deploy\binaries
        cp build\guitar-configurator.exe deploy
        windeployqt deploy\guitar-configurator.exe -qmldir=.
        xcopy /O/X/E/H/K/I deploy installer\packages\net.tangentmc.guitar_configurator\data
        binarycreator -c installer\config\config.xml -p installer\packages win_installer_%arch%.exe