name: Build Windows

on: [push]

jobs:
  build-win:
    runs-on: windows-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with: 
        modules: qtserialport qtquickcontrols2 
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: build and bundle
      run: |
        call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        qmake -config release -tp vc -spec win32-msvc guitar-configurator.pro
        msbuild guitar-configurator.vcxproj /t:Build /p:Configuration=Release
        mkdir deploy
        xcopy firmware /O/X/E/H/K/I deploy\firmware
        xcopy binaries\win /O/X/E/H/K/I deploy\binaries
        cp release\guitar-configurator.exe deploy
        windeployqt deploy\guitar-configurator.exe -qmldir=.
        xcopy /O/X/E/H/K/I deploy installer\packages\net.tangentmc.guitar_configurator\data
        python -m aqt tool windows tools_ifw 3.1.1 qt.tools.ifw.31
        mkdir artifacts
        .\Tools\QtInstallerFramework\3.1\bin\binarycreator -c installer\config\config.xml -p installer\packages artifacts\win_installer.exe
      shell: cmd
    - uses: actions/upload-artifact@v1
      with:
        name: windows
        path: artifacts